### ISSUE TITLE
"contribution process" link is 404

### ISSUE THREAD

**Issue by Tan90909090** [dotnet/apireviews#118]
> The way you contribute to this is by proposing APIs to be added. To do this, you simply follow the contribution process as [described here].

The link is [https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md), which is 404.
I think that current url may be [https://github.com/dotnet/runtime/blob/master/CONTRIBUTING.md](https://github.com/dotnet/runtime/blob/master/CONTRIBUTING.md) or [https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md).

**Comment by terrajobst** [comment]
@Tan90909090 

Thanks for reporting! Just fixed.
