### ISSUE TITLE
Review notes for 3 Jun 2024 are missing

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/apireviews#129]
The bot has not been run for the 3 Jun 2024 API review.

**Comment by bartonjs** [comment]
The tool that generates the review notes is currently offline.  My understanding is that it's because GitHub made some API breaking changes.  When it comes back we'll (try to) run it retroactively.

**Comment by colejohnson66** [comment]
Got it. Should we close this issue then? Or leave it until the bot is back online?
