### ISSUE TITLE
Improve repository structure

### ISSUE THREAD

**Issue by terrajobst** [dotnet/apireviews#31]
This repo is used for publishing design notes. API review are part of this, but it's not the only area we publish notes for. For instance, we intend to publish notes for features and bug [we considered for .NET Framework](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/triage.md#porting-to-net-framework) but decided against porting.

Suggested changes:
- Rename repo to `design-notes`
- Change structure:

```
\
├───core
│   ├───2015
│   │   └───2015-11-24-networking
│   │           All ASPNET5 contracts.md
│   │           Desktop_vs_ASPNET5 contracts.md
│   │           README.md
│   │
│   └───2016
│       └───2016-01-08-metadata
│               README.md
│
└───netfx
    └───2016
        └───2016-01-01-port-triage
                README.md
```

Thoughts?

**Comment by akoeplinger** [comment]
Sounds good to me. I wonder whether adding a subfolder under core specifically for `api-reviews` makes sense or do you think this will always be chronological?

**Comment by terrajobst** [comment]
I was thinking about this; the problem is that many meetings review APIs and/or regular design decisions. The boundaries are that fixed.

Also, we'd also review APIs that go into netfx, so I guess separating by platform then chronological would make sense.

**Comment by terrajobst** [comment]
@staceyhaffner, what are your thoughts?

**Comment by staceyhaffner** [comment]
The structure makes sense to me.

**Comment by terrajobst** [comment]
Sweet, will make the changes then.

**Comment by terrajobst** [comment]
I've simplified the structure by not having the top-level targets.
